---
language: node_js
node_js:
  - "6"

sudo: false
dist: trusty

addons:
  chrome: stable

cache:
  yarn: true

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1
    - secure: EYaa9XxKkfJbQENuQPNFAIIieMWBiSknGCO9he8MH8ZHbqJODTjFixJnD5ZYLZCXH67SmjorBneznQHp8Xaf0aIuHbRhRY/MOUzqEWw12MmexW1kJF5wX+oxEnvzoiVAUJLNTIQi+g5WN43YBleASKMjUPa2i/3GBIcTlsVdf3U=
    - secure: g+Qh9jUTpK1yFpcZi9O8rsybfqv3TFE2hTFvG8XZ+QaQYBLLZ52JfhsJhdI0cvRRp7qWOhzE784iadkPWgvhj8c0/N/af5ZrSP3ceiv6RKqSUG2/iQyzX/qUh3vqrZ7a4xTsELTwswQtR+sA+I+DQVVlnqcCqYTAW2SFR/D4H8o=
    
stages:
  - test
  - ember debug test

jobs:
  fail_fast: true
  allow_failures:
    - env: EMBER_TRY_SCENARIO=ember-canary

  include:
    # runs tests with current locked deps and linting
    - stage: test
      script:
        - yarn lint:js
        - yarn test

    # runs tests against each supported Ember version
    - stage: ember debug test
      env: 
        - EMBER_TRY_SCENARIO=ember-2.7
        - EMBER_TRY_SCENARIO=ember-lts-2.8
        - EMBER_TRY_SCENARIO=ember-lts-2.12
        - EMBER_TRY_SCENARIO=ember-lts-2.16
        - EMBER_TRY_SCENARIO=ember-lts-2.18
        - EMBER_TRY_SCENARIO=ember-release
        - EMBER_TRY_SCENARIO=ember-beta
        - EMBER_TRY_SCENARIO=ember-canary
        - EMBER_TRY_SCENARIO=ember-default
      script:
        - node_modules/.bin/ember try:one $EMBER_TRY_SCENARIO --- node_modules/.bin/ember test --filter="Ember Debug"
        

before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH=$HOME/.yarn/bin:$PATH
  - yarn global add bower

install:
  - yarn install --ignore-engines
  - bower install

after_success:
  - test $TRAVIS_BRANCH == "stable" && yarn run upload
